### ISSUE TITLE
Improve guide example

### ISSUE THREAD

**Issue by kARAT97** [jooy2/vitepress-sidebar#104]
My thought is to improve the guide usability with a very simple method, you already have the configuration examples which are great and you have a demo which is also great but I feel like a crucial component there is missing.

You should input a code block into the guide and/or demo site that references the exact configuration utilized in the demo site.
As an example, I'm looking into the same sort of segmentation of sidebars as on the demo site, with the "CSS" "Javascript" and "Markdown index" sections being in bold with rulers above them separating the sidebars but can't easily figure out whether that's performed through the markdown syntax in titles or by utilizing multiple sidebar configuration displayed on the same site.

Having the code snippet used on the demo site would immediately show me how it's performed.

**Comment by jooy2** [comment]
Hello, thank you for your valuable feedback.

As of 2024, the documentation page has undergone a major overhaul, removing ambiguous descriptions and making it easier to find options.
I don't yet have code examples for each option, but this will be added gradually as needed.

I'm closing this issue because it's more or less up to date and i can't link to an actual commit.
However, i will continue to improve the documentation in the future.

Regards,
