### ISSUE TITLE
Feature Request:Missing indent

### ISSUE THREAD

**Issue by damokeris** [jooy2/vitepress-sidebar#168]
**Describe the bug** A clear and concise description of what the bug is：侧边栏折叠/展开，目录没有缩进，体现不出层级关系。
![image](https://github.com/user-attachments/assets/966ff980-1021-430e-a858-00fc9e56cb46)

**Expected behavior** A clear and concise description of what you expected to happen：预期应该像下面这样：
![image](https://github.com/user-attachments/assets/6a8dc2f4-fd6b-45ad-bdfa-d5fd63538069)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Edge

**Comment by jooy2** [comment]
Hello, thank you for using the `vitepress-sidebar` plugin.

This issue doesn't seem to be reproducible in general, could you please provide an example of a reproducible project, it would help us to identify the issue.

Otherwise, please add debug info to your settings as follows, then copy the output to the console and the full settings code and leave it in the comments.

```javascript
...
themeConfig: {
    logo: { src: '/logo-32.png', width: 24, height: 24 },
    // Single sidebar example
    sidebar: generateSidebar({
      ...
      debugPrint: true, // <------------------------------------------ Add this line
    }),
}
...
```

Regards,

**Comment by damokeris** [comment]
亲爱的开发者：
感谢您在百忙之中抽出时间回复我的小问题。

我按照您说的进行了配置，现在vitepressSidebarOptions看起来像这样：
![image](https://github.com/user-attachments/assets/2327c8e6-4159-42a4-89a0-ff9386c700d3)

在运行 `npx vitepress dev docs` 命令后，输出的调试信息如下：
![image](https://github.com/user-attachments/assets/62590b8e-2906-4235-a0f5-ecdc6646c480)

本地浏览的最终效果如下：
![image](https://github.com/user-attachments/assets/f08d148d-f1a4-4565-9770-360d630c43dd)

但是，我注意到，我本地的文件结构如下：
![image](https://github.com/user-attachments/assets/2fae38b7-4460-40d8-9ee5-24e6a2965a8d)

所以，我期望最终效果应当像这样：
![demo](https://github.com/user-attachments/assets/dcf5e3df-75b5-434a-916c-d340354f6aa0)

顺便地，我附上了一个最小可运行的demo
[vitepress.zip](https://github.com/user-attachments/files/16676877/vitepress.zip)

Thanks🍭

**Comment by jooy2** [comment]
Hello, Thank you for the detailed explanation and examples! It helped me to see the problem clearly.

# 1. Folder hierarchy display issues

First, to address the hierarchy issue, the current sidebar is structured correctly according to the documentation.
However, it appears that VitePress' default theme treats the second level of directories as the same hierarchy as the first level, as described above.

So this is not caused by the plugin, but what I have found is that if I implement one more level of directory (i.e. extend it to a third level), then the directory and file hierarchy will display correctly from then on.

**Project structure:**

![image](https://github.com/user-attachments/assets/d0c89fd1-efe3-48c4-879c-d81c090a8aff)

**Result:**

![image](https://github.com/user-attachments/assets/65caefd3-d8d6-4bb8-be1a-3d13d48e5f82)

To fix this issue permanently, you can open an issue in [VitePress' issue tracker](https://github.com/vuejs/vitepress/issues), or try the temporary workaround with Custom CSS below:

## 1.1. Workaround

You can override VitePress' default theme with custom CSS to fix the problem (See: https://vitepress.dev/guide/extending-default-theme#customizing-css). Since it's the collapsible group menu at level-0 that's causing the problem, we'll give it some arbitrary padding.

First, add a `.vitepress/theme` directory. Then create an `index.js` (or `index.ts`) file in this directory. Write this file as follows

```javascript
import DefaultTheme from 'vitepress/theme'
import './custom.css'

export default DefaultTheme
```

Now create a custom CSS file for overriding and edit it like below: `.vitepress/theme/custom.css`

```css
.VPSidebarItem.level-0.collapsible .items {
    padding-left: 16px;
    border-left: 1px solid var(--vp-c-divider);
    border-radius: 2px;
    transition: background-color 0.25s;
}
```

The `padding-left` is for the left margin, and the rest of the styles are based on the default VitePress theme for the vertical divider.
(Note: The vertical divider is separated into a separate div, but we're going CSS-only here, which may cause unintended behavior).

**File structure after applying:**

![image](https://github.com/user-attachments/assets/62ec6e53-2b52-4995-9ef5-2283864465d6)

Now, when you run VitePress, you should see something like this:

![image](https://github.com/user-attachments/assets/5d18be8a-4af7-4683-8b54-5db336434b6f)

# 2. Menu collapsing issues

This is a feature of VitePress.

You can collapse the folder menu for all or certain steps, depending on the collapsible setting in the sidebar. The option values for `collapsed` are `null` (which has different results than not defining it), `false`, and `true`, each with the following results

![image](https://github.com/user-attachments/assets/d23c25fd-4a0a-43a7-959b-3498cb6a3896)

I hope the above explanation fulfills your requirements and resolves your issue. If you have any questions, feel free to leave a comment.

Regards,

**Comment by damokeris** [comment]
亲爱的开发者：
感谢你为我的问题作出的回答，我现在已经明白了。

Thank you，
