### ISSUE TITLE
[Feature Request] Display directories/folders last

### ISSUE THREAD

**Issue by mrleblanc101** [jooy2/vitepress-sidebar#173]
Currently:
<img width="293" alt="Screenshot 2024-09-12 at 11 44 23 PM" src="https://github.com/user-attachments/assets/d3b6ec10-3ae6-49d3-b1b4-bd3774a6010e">

What I would like:
<img width="295" alt="Screenshot 2024-09-12 at 11 48 46 PM" src="https://github.com/user-attachments/assets/838c2472-19cf-45b0-ba69-e6fba379170e">

**Comment by jooy2** [comment]
Hello! Thank you for using `vitepress-sidebar`.

This feature was implemented in version `1.27.0` with the added `sortFolderTo` option.

According to your requirement, `sortFolderTo: 'bottom'` allows you to position the folder to the bottom.
(The folder/file separation is done last, after the sorting is done by the other options).

This is an issue for a feature request, so if you find any new issues with this feature, please open a new issue. Since the implementation is complete, i'll mark the issue as complete.

Regards,
