### ISSUE TITLE
Add support for sorting folders

### ISSUE THREAD

**Issue by Dr-Octopus-dev** [jooy2/vitepress-sidebar#193]
Is there a way to sort folders by giving number?

**Comment by jooy2** [comment]
Hello, Thank you for using `vitepress-sidebar`!

Folders and files can be sorted in different ways. Typically, you can manually sort folders and files in the order you want by using the [sortMenusByName](https://vitepress-sidebar.cdget.com/guide/options#sortmenusbyname) option.

However, if you want to do the sorting automatically for a large number of files, you can do it using `frontmatter`, or by using a numeric prefix before the file name.

## Using frontmatter

First, since folders do not have frontmatter configured, there is a workaround by creating an `index.md` file.

If you want the folder name displayed on the menu to be the title from the index file, see the option [useFolderTitleFromIndexFile](https://vitepress-sidebar.cdget.com/guide/options#usefoldertitlefromindexfile).


```text
/
├─ package.json
├─ src/
├─ docs/
│  ├─ .vitepress/
│  ├─ abc/
│  │  ├─ abcdef.md
│  │  └─ index.md
│  └─ def/
└─ ...
```

Below is the corresponding part of the `abc/index.md` file:

```text
---
title: this is folder menu name
order: 1
---
```

```javascript
// `.vitepress/config.js`
const vitePressOptions = { /* ... */ }

const vitePressSidebarOptions = {
  // Use the `title` tag in frontmatter as the menu name.
  useTitleFromFrontmatter: true,
  // The folder menu name is taken from the `index.md` that exists in the top-level path of that folder.
  useFolderTitleFromIndexFile: true,
  // Sort by the numeric value of the `order` tag in frontmatter.
  sortMenusByFrontmatterOrder: true,
  // Set the value to `false` to not show the `index.md` file in the folder in the menu. (Default=false)
  includeFolderIndexFile: false
}

export default defineConfig(
  withSidebar(vitePressOptions, vitePressSidebarOptions)
);
```

## Using numeric prefixes

Prefix the folder name with a number and sort the menu by that number. You must use the [sortMenusOrderNumericallyFromTitle](https://vitepress-sidebar.cdget.com/guide/options#sortmenusordernumericallyfromtitle) option.

You can also use the [removePrefixAfterOrdering](https://vitepress-sidebar.cdget.com/guide/options#removeprefixafterordering) option if you don't want the numbers in later folders to appear in the menu.

```text
/
├─ package.json
├─ src/
├─ docs/
│  ├─ .vitepress/
│  ├─ 1-abc/
│  ├─ 2-def/
│  ├─ aaa.md
│  └─ index.md
└─ ...
```

```javascript
// `.vitepress/config.js`
const vitePressOptions = { /* ... */ }

const vitePressSidebarOptions = {
  // Ensure that the names `1-`, `10-`, `2-`... are correctly sorted by number.
  sortMenusOrderNumericallyFromTitle: true,
  // Don't show `1-`, `2-` in the menu after completing the sort.
  removePrefixAfterOrdering: true,
  // A separator to determine the number in the file name. Use `.` for `1.`, `.` for `1-`, and `-` for `1.`.
  prefixSeparator: '-',
}

export default defineConfig(
  withSidebar(vitePressOptions, vitePressSidebarOptions)
);
```

---

If the above suggestions do not meet your needs, please provide a specific example in your feature request.

Regards,

**Comment by Dr-Octopus-dev** [comment]
It's enough for me, thank you a lot!

**Comment by jooy2** [comment]
Thanks for letting me know! If you have any new issues or questions, please feel free to create a new issue!

I'll consider this issue closed as complete.
