### ISSUE TITLE
`rootGroupCollapsed` no effect when `collapsed` is undefined

### ISSUE THREAD

**Issue by alephpi** [jooy2/vitepress-sidebar#81]
version 1.10.0
When 
```
rootGroupCollapsed: true,
collapsed: true or false
```
The collapse button for root group is displayed
![image](https://github.com/jooy2/vitepress-sidebar/assets/61275421/c298fabf-716b-4a4a-bd50-fa99c6035995)

While
```
rootGroupCollapsed: true,
// collapsed is not defined
```
The collapse button for root group is not displayed.
![image](https://github.com/jooy2/vitepress-sidebar/assets/61275421/5aa187c2-191b-4347-b1d4-6fc88e83cd6b)

Is this an expected behavior?
If so, would you point out in the readme file? since I thought it was an independent setting.

**Comment by jooy2** [comment]
Hello,
Thank you for reporting the issue.

This issue has been fixed in version 1.10.1.

Fixed so that the `rootGroupCollapsed` option is applied regardless of the value of the `collapsed` option. Note that the collapse state of the root group may appear to be expanded regardless of the option if the current page is located on a page within that group.

Please upgrade your package and check if the issue persists.

Thanks!
