### ISSUE TITLE
enhanced multi-sidebar output

### ISSUE THREAD

**Issue by xiankq** [jooy2/vitepress-sidebar#83]
```js
{
  '/guide/': [
    {
      text: 'Guide',
      items: [
        { text: 'Index', link: '/guide/' },
        { text: 'One', link: '/guide/one' },
      ],
    },
    // It seems that generating the following section is not supported
    // ===↓↓↓↓↓↓↓↓↓↓↓↓===
    {
      text: 'Guide2',
      items: [
        { text: 'Index2', link: '/guide2/' },
        { text: 'One2', link: '/guide2/one' },
      ],
    },
  ],
}


```

**Comment by jooy2** [comment]
Hello, Thank you for using `vitepress-sidebar`.

Does the above code mean that no section has been created for '/guide2/'? Please share the settings and current directory tree of `vitepress-sidebar` to further understand the issue.

To properly set up multiple sidebars, see the section in the README.md below:

https://github.com/jooy2/vitepress-sidebar#multiple-sidebars-how-to

To use multiple sidebars, the options must be an array of objects, each with their own settings.

Regards,

**Comment by jooy2** [comment]
Hello.
The sidebar menu heading issue has been improved in the latest version `1.14.0`, please see the `CHANGELOG.md` file for details.

Since this issue is no longer receiving responses, I'll consider it closed.
However, if you continue to experience problems or encounter new issues, please feel free to create a new issue.

Thanks.
