### ISSUE TITLE
Option to capitalise menu names

### ISSUE THREAD

**Issue by husayt** [jooy2/vitepress-sidebar#95]
This sidebar generator is really coming to shape now. There is an option called `hyphenToSpace`.  Will be great to add `capitaliseFilenames` and `capitaliseFolders` which will make first letter capital and that will be a nice touch.

Thank you

**Comment by husayt** [comment]
there is a very handy library, which can help and provide many options for this:

https://github.com/blakeembrey/change-case

**Comment by jooy2** [comment]
Hello! Thank you for using `vitepress-sidebar`.

The feature you requested can be configured via the `capitalizeFirst` option, which already exists, and the `capitalizeEachWords` option, which is new in version `1.18.0`.

Currently, i do not distinguish between options for each of the possible files and folders. For files, you can use, for example, Markdown's h1 heading or Frontmatter's title tag to get the division.

If you have any new issues with the feature, please open a new issue. I'll close this one in a few days.

Regards,

**Comment by husayt** [comment]
@jooy2 this was really what I needed. It works great for me. 

one question I have is if in case I need to override for files, I can always add title info into frontmatter and with useTitleFromFrontmatter that will work. Is there similar way to do it for folders?

**Comment by jooy2** [comment]
네, 폴더 구조 특성상 파일만큼 손쉽게 제목을 사용자 지정하지는 못하지만 한가지 방법이 있습니다: `usefoldertitlefromindexfile` 옵션을 사용합니다.

`usefoldertitlefromindexfile` 옵션을 사용하면 해당 폴더에 있는 `index.md` 파일을 찾습니다. 그리고 해당 파일의 제목을 가져옵니다. (frontmatter or markdown h1 tag)

```
generateSidebar({
  documentRootPath: 'example',
  scanStartPath: 'javascript',
  useTitleFromFileHeading: true,
  hyphenToSpace: true,
  excludeFolders: ['vitepress-how-to']
});
Folder
├─ file-a
└─ index.md

====================== index.md ====================== 
# Folder Title

content...
```

`index.md` 파일은 `includeFolderIndexFile` 옵션이 `false`일 경우 숨겨지기 때문에 폴더 메뉴에 대해 인덱스 링크를 구성하지 않는다면 `index.md` 파일은 폴더 정보를 구성해두기에 좋은 파일이 될 수 있습니다.

2. ``

**Comment by jooy2** [comment]
@husayt 

Yes, due to the nature of the folder structure, you can't customize the title as easily as you can a file, but there is one way: Use the `useFolderTitleFromIndexFile` option.

The `useFolderTitleFromIndexFile` option will find the `index.md` file in that folder and get the title of that file. It uses the title information from the Frontmatter or Markdown h1 tag in the index.md file.

The `index.md` file can be hidden from the menu list if the `includeFolderIndexFile` option is `false` (default is `false`).

In the example below, the actual menu display title of the Folder is `Index-md Title`.

Folder structure:

```
Folder
├─ file-a
└─ index.md
```

`vitepress-sidebar` options:

```javascript
generateSidebar({
  documentRootPath: 'example',
  useTitleFromFileHeading: true,
  useFolderTitleFromIndexFile: true // <<------- Add this
});
```

`index.md`:

```markdown
# Index-md Title

`index.md` file's content...
```

Results:

```javascript
[
  {
    text: 'Index-md Title',
    items: [
      {
        text: 'File A', // `file-a` title
        link: '/file-a'
      }
    ]
  },
```

Regards,
